spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/bcsd?serverTimezone=Asia/Seoul
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false